### ISSUE TITLE
Suggestion : Home Screen Layout

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/SantasMagicNight#173]
The logo does not fit in theme with the rest of the visuals displayed on the home screen. A suggestion here would be to have a custom done 2d home screen, you can maybe just use the same art made here but have it done in 2d and make it simple but sweet.  The gift moving and the title, both make it seem unpolished since the title style doesn't fit. The home screen should have an amazing feel to it to set the player in the right mood. If you want to use the current background, maybe remove the gift and use a small home screen template and blur the current background a little ?  Also we can do something creative here with the Exit button too like have 2 candy canes cross each other making an X and write Quit or Exit next to it in case the player gets confused.

Ref to the image provided, we could have the text written like that but with a fancier font similar to the logo design so it looks like one thing. We can have a scene setup in the background and the camera rotates around ( similar to how the camera rotates in minecraft home screen) showing the screen off. The background however will be blurred so the main focus will be on the home screen text and it wont make it too messy either. This setup works great for mobile games as well.

![image](https://user-images.githubusercontent.com/56066524/98804018-9a941b00-243b-11eb-834f-1d9e4e90d448.png)

**Comment by mustucontractor** [comment]
Maybe we can have all the text in this style ? I love it!! 
![image](https://user-images.githubusercontent.com/56066524/98804097-bb5c7080-243b-11eb-8568-df4f02aacc6e.png)

**Comment by SilasReinagel** [comment]
We'll consider this.

**Comment by SilasReinagel** [comment]
We're going with the same general menu.

Having some 3D and lighting enhancements made. New menu should be blazingly fast.
