### ISSUE TITLE
Bug : Incomplete Level

### ISSUE THREAD

**Issue by mustucontractor** [EnigmaDragons/SantasMagicNight#178]
Not sure what level it is but I don't think it is possible.
![image](https://user-images.githubusercontent.com/56066524/98805783-2018ca80-243e-11eb-822b-6354cff7ad18.png)

**Comment by mustucontractor** [comment]
It is level 12

**Comment by SilasReinagel** [comment]
Attached solution video in Discord Channel. Awaiting confirmation that level puzzle layout is the same.
